### PR TITLE
Create .travis.yml

### PR DESCRIPTION
**Pull request by cclauss**
This will automatically run [flake8](https://flake8.pycqa.org) tests and `pytest` on every pull request to this repo.  This will help contributors know if their submissions would break the build.  To turn on this free service, you would need to do steps 1 and 2 of https://docs.travis-ci.com/user/getting-started/

The tests will run **after** #69 is accepted.

### CODE REVIEW

**Comment by LazoCoder** [comment]
I've never used anything like this before so I'm not sure what its implications are. I also don't believe the project is large enough that something like this is required. Furthermore, unittest.py is not sophisticated enough to do anything useful without being accompanied by a human imo.

**Comment by cclauss** [comment]
The implications are quite straightforward...  whenever you or someone makes a change to the Python code in the repo, a series of tests are run on a free server in the cloud to make sure that no syntax errors or code style error were added to the code.  Automated testing is key to delivering quality software these daze...  A funny point or view from several years ago: https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo

**Comment by LazoCoder** [comment]
I'll have to do some research on this.

**Comment by cclauss** [comment]
https://travis-ci.org/cclauss/flake8_for_pt should give you an idea of what the test output looks like.

**Comment by samosaara** [comment]
I mean i completely  agree with @cclauss that are lots of benefits of having a travis CI support on any repo, plus it's free and doesn't hurt. The thing is, the project doesn't have proper unit testing yet to benefit from continuous integration tools 'properly', so CI would only help if added alongside proper unit testing.

**Comment by cclauss** [comment]
@samosaara the current flake8 tests will find syntax errors.

I have had the Travis file include pytest and I have curettes three test cases in unittest.py

**Comment by cclauss** [comment]
The tests will run after https://github.com/LazoCoder/Pokemon-Terminal/pull/69 is accepted.

**Comment by cclauss** [comment]
@LazoCoder To turn on this free service, you would need to do steps 1 and 2 of https://docs.travis-ci.com/user/getting-started/

**Pull request merged**
