### PR TITLE
Allow installation with pip

### PR DESCRIPTION
**Pull request by caedus75**
This PR has a number of changes to the repository so Pokemon-Terminal script can be installed with `pip`.

- move all code, data and images to `pokemonterminal` python package.
- move all tests to `tests` package.
- add `setup.py` file.
- recreate `pokemon` and `ichooseyou` executables.

All `import` statements are updated against the new package structure.

The new structure allows a cleaner install and proper python package. It's still possible to use the script directly from the cloned repo.

The version number in `setup.py` and `pokemonterminal/__init__py` is intentionally low because this project don't have any formal release yet, just the code in development. Once it's decided how/when to publish a new version, that value can be easily updated.

This is related to #16 .

### CODE REVIEW

**Comment by cclauss** [comment]
Very impressive!

**Comment by samosaara** [comment]
Again I also agree, but the thing is, the pull requests are starting to pile up, and conflict. This isn't compatible with the unova pokemon additions... witch in turn isn't compatible with my rework. Great work here, it's just gonna be a pain to merge all this onto master.

**Comment by LazoCoder** [comment]
I like this. Its about time that we added pip and put the tests in a package. If it wasn't for these damn merge conflicts I would have accepted the pull immediately.

**Comment by caedus75** [comment]
I rebased my branch on top of master and fixed the conflicts. It's good to merge now.

**Pull request merged**
