### PR TITLE
Add proper feh support

### PR DESCRIPTION
**Pull request by sylveon**
This works on other WMs too, such as OpenBox.

peek 2018-01-03 12-00

<sup>Don't mind the blurring I haven't finished configuring compton</sup>

### CODE REVIEW

**Comment by sylveon** [comment]
It would also be possible to implement restoring the other wallpaper by running ~/.fehbg, but the wallpaper adapters don't have support for restoring so I left it out

**Comment by samosaara** [comment]
Hey I implemented i3wm not feh on purpose, feh is a software not a WM or a DE, I have gnome, am running gnome, and I also have feh, that would make it way too confusing. I know the majority of the tilings WM's use feh and it would be extremely convenient to implement them all in a fell swoop like that, but that will break other WM's. If you want to implement other tiling WM's just make a new adapter that extends i3wm and override the `isCompatible` method

**Comment by sylveon** [comment]
But then if feh is absent it will output a i3-specific message

**Comment by sylveon** [comment]
I guess a solution would be giving this adapter a low priority. So it only gets attempted last, and if you have something like GNOME installed, it will always end up picking gnome

**Comment by sylveon** [comment]
@samosaara I added a WM check in it, can you take another look?

**Comment by samosaara** [comment]
Much better, but like since we're already here, why not add more WM's? bspwm, awesome, sway...

**Pull request merged**
