### PR TITLE
added ubuntu,official spin of ubuntu,linux mint,etc 

### PR DESCRIPTION
**Pull request by siddht1**
added terminology installation,

### CODE REVIEW

**Comment by LazoCoder** [comment]
I appreciate your intention at contributing to this project but this only adds more clutter to the readme without providing much value. @samosaara already mentioned Terminology in the Linux instructions that he provided (right above your contribution) and I don't think we need to give people instructions as to how to install terminal emulators. Furthermore, this broke the formatting of the rest of the readme. Scroll down and see for yourself: [link](https://github.com/siddht1/Pokemon-Terminal/blob/49733d4dd854a87a610f756cdf4a8048af61032e/README.md).

**Comment by siddht1** [comment]
ok if this would have succeed my next commit would be and still is going to be add new pokemon like greninja,greninja ash form,rotom(pokedex),zygarde,z2,squishy,

**Comment by siddht1** [comment]
Ok i would re edit the readme and would also add fedora,rhel, etc for both terminology and tilda

**Comment by charlesmilette** [comment]
Why would you need to specify it for each distro ever? You can just specify
they need a compatible terminal emulator, and let them install it
themselves.

**Comment by siddht1** [comment]
I have actually added them as a ppa for ubuntu so it would work for my linux mint too,debian is also done.I would pull the deb files shortly.I also use fedora so I have created a custom rpm.     This way a user doesnt have to manually do anything but just let it upgrade by itself.

**Pull request closed without merging**
