### PR TITLE
Feature: Optimize Images

### PR DESCRIPTION
**Pull request by marcobiedermann**
I've optimized all images using [ImageOptim](https://imageoptim.com) without losing any quality which saves a lot of data.

image

Saves 7.3 MB / 37.1 MB ~19.8 %

### CODE REVIEW

**Comment by charlesmilette** [comment]
What about the images in `Samples` too?

Le jeu. 22 juin 2017 07:46, Marco Biedermann <notifications@github.com> a
écrit :

**Comment by marcobiedermann** [comment]
@charlesmilette Yes, I've optimized all images.
See: https://github.com/LazoCoder/Pokemon-Terminal/pull/54/commits/9ba077327f6748350ca285f0f48954dd0de9d12d#diff-518

**Comment by charlesmilette** [comment]
Nevermind then, it's just my email not showing them

**Comment by samosaara** [comment]
Seems too good to be true for me, haven't you noticed any artifacts and or losses in quality and or color fidelity?

**Comment by marcobiedermann** [comment]
@samosaara Not at all. ImageOptim uses lossless compression.

> Reduces image file sizes — so they take up less disk space and down­load faster — by applying advanced compression that preserves quality.

https://imageoptim.com/mac

**Comment by marcobiedermann** [comment]
ImageOptim is the best tool out there for image optimization. On "best" settings it takes a bit longer but will reduce the filesize a lot.
Took around 4-5 hours to run all images through

**Comment by LazoCoder** [comment]
After experimenting with ImageOptim I have found that it has much better compression and quality preservation than pngquant. The images that you compressed have already been compressed by pngquant and so the quality loss that was created by pngquant had been carried over through ImageOptim. What I did instead was that I compressed the *original* images using ImageOptim (I cut out the pngquant middleman).

I experimented with ImageOptim's settings a bit and I found that with a 5% quality loss it can reduce the images even more *while still having higher quality than pngquant's compression*. So the result is a total of 21mb (from 37mb) with better quality than before (IMO). I tested this on a macbook with retina display.

You can see here for yourself. The following image was compressed by pngquant. If you download it and zoom in, you can see faint horizontal lines in the background across the entire image. Honestly, its quite hideous on my macbook and its 48kb.
149-pngquant

The following image is compressed by ImageOptim. It has no horizontal lines and its 31kb.
149-imageoptim

Even though I am declining your pull request, I'm giving you credit in the readme since I would not have known about ImageOptim otherwise.

**Comment by marcobiedermann** [comment]
@LazoCoder Thank you Lazo for your detailed explanation.
I did not see the thin hairlines inside the images. I am working on a non retina display.
Thank you very much for giving me credit. If there is anything else I can do for you, feel free to ping me :)

**Pull request closed without merging**
