### PR TITLE
Show pokemon in random order in slideshow

### PR DESCRIPTION
**Pull request by kamil157**
I think slideshow would be cooler if it was in random order. This way it's less repetitive and doesn't end at Arceus, but loops indefinitely. If you like the old slideshow this could be a separate command instead.
Btw 0.25 seconds delay seems way too fast, but I didn't wanna change it in the same commit/PR.

### CODE REVIEW

**Comment by LazoCoder** [comment]
To be honest, the only reason why I implemented the slideshow function in the first place was to test/debug things and make sure that each picture was loading properly. That's why the delay is 0.25 seconds, so that I can run through them all fast. I didn't think that people would actually use this function. What do people even use it for?

**Comment by gvela024** [comment]
I'd use it if it was like 5 minute delay. This would make it long enough not to be distracting but short enough to be exciting between terminal stuff that I was doing.

**Comment by dosman711** [comment]
I'd suggest a slightly different change, so that it still has an end
```
r = list(range(start, end))
random.shuffle(r)
for x in r:
...
```

Also +1 for being someone who would likely use this on a long timer :)

**Comment by LazoCoder** [comment]
Ok, random slideshow is fine but I would like to also have the old one as well for testing purposes.

**Pull request closed without merging**
