### PR TITLE
change pokemon db file from plain text to json format

### PR DESCRIPTION
**Pull request by caedus75**
Use a structured file format to hold all pokemon's information.

This allow new data to be easily written and read from the database, if needed.

If you guys think it needs any change, let me know.

### CODE REVIEW

**Comment by cclauss** [comment]
@caedus75 Thanks a lot for this contribution -- both the code and the data look solid.  However, my sense is that we would be adding a lot of complexity (the PR is +4,958 −515 lines) but not getting much new value for our usecases.  Perhaps the others see benefits that I am not seeing.

For us, the data in `pokemon.txt` is read-only and is quite compact yet human readable in its current form.  I am a huge fan of json but in this case, we are not shipping our data to other people/systems for them to use in a different context.  If we were then the self-documenting nature of json would help.  Today, we just merely want to read in data and use it to show images to users.

I look forward to the feedback from you and other.  Perhaps I am missing something here.

**Comment by caedus75** [comment]
I understand and agree with everything you said. I thought about it before opening this PR because it's really a big change with no real benefit right now.

What I noticed about the current format and made change the database to something else is the lack of distinction between a field separator and a null value. Right now there is no need for it, the database hold few data about the pokemons and if one have one or two types, it doesn't matter because there is no more data stored. It's simple enough to split() and strip() the text and move on.  
If a new filter is implemented, like #37, or filter by starter pokemon, the database will need to be updated to be explicit about null values, to be able to keep fields with one or more values in it.

Perhaps it's better to wait until there's a real need to touch the database and then discuss how to update it.

**Comment by cclauss** [comment]
Is there something else in the codebase that you want to work on?

**Comment by caedus75** [comment]
Oh, don't worry about it, I'm following development and studying the changes, I'll find something to work on!

Closing this PR now.

**Pull request closed without merging**
